import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const api = createApi({
  baseQuery: fetchBaseQuery({
    baseUrl: `${process.env.NEXT_PUBLIC_API_BASE_URL}/api/v1`,
    credentials: "include",
  }),
  reducerPath: "api",
  tagTypes: [
    "User",
    "Companies",
    "Company",
    "CompanyInvites",
    "CompanyInvite",
    "CompanyUsers",
    "CompanyUser",
    "CompanyDashboard",
    "CompanySalesVolume",
    "Accounts",
    "Account",
    "AccountMetrics",
    "AccountDetails",
    "Products",
    "Product",
    "ProductsToRestock",
    "StockHistoryList",
    "StockHistoryItem",
    "Bookings",
    "Booking",
    "Orders",
    "Order",
    "Invoices",
    "Invoice",
    "InvoiceTemplate",
    "InvoiceNumberSeries",
    "AccountsReceivables",
    "AccountsReceivable",
    "Sales",
    "Sale",
    "Payments",
    "Payment",
    "PendingExcesses",
    "PendingExcess",
    "Refunds",
    "Refund",
    "CreditMemos",
    "CreditMemo",
  ],
  endpoints: () => ({}),
});
